seed: 42
name: 'GasMap'
dataset:
  type: 'gasmaps'
  path: '/mnt/ceph/users/dmohan/dreams/data/gasmaps'
  mean: 0.9676
  std: 0.0730
  train_n_files: 700
  train_n_galaxies: 343
  val_n_files: 100
  val_n_galaxies: 100

training:
  epochs: 600
  batch_size: 32
  num_workers: 64
  prefetch_factor: 4
  drop_last: True
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: 'adam'
  loss_function: 'mse'
  patience: 2
  factor: 0.9



model:
  input_shape: [1, 512, 512]
  output_size: 1
  architecture: 'ResNet18'
  # layers: add dropout later
    # - type: Conv2D
    #   filters: 32
    #   kernel_size: [3, 3]
    #   activation: relu


results:
  path: '/mnt/ceph/users/dmohan/dreams/results/gasmaps/exp1'